# Menggunakan base image Node.js versi 18
FROM node:18

# Set working directory di dalam container
WORKDIR /usr/src/app

# Salin package.json dan package-lock.json untuk instalasi dependensi
COPY package*.json ./

# Install dependensi
RUN npm install --production

# Salin seluruh kode aplikasi ke dalam container
COPY . .

# Ekspos port aplikasi (port default untuk Cloud Run adalah 8080)
EXPOSE 3000
# Set environment variable untuk Cloud Run
ENV PORT 3000

# Jalankan aplikasi
CMD ["node", "server.js"]